# Generated by Django 4.2.1 on 2023-07-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robloxId', models.CharField(max_length=50)),
                ('banReason', models.TextField(blank=True, max_length=130, null=True)),
                ('banStart', models.DateTimeField(auto_now_add=True)),
                ('banLength', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='banType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certName', models.CharField(max_length=100)),
                ('certId', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='robloxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robloxId', models.CharField(max_length=50, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('has_drivers_license', models.BooleanField(default=False)),
                ('banData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.baninstance')),
                ('userCerts', models.ManyToManyField(to='core.certification')),
            ],
        ),
        migrations.AddField(
            model_name='baninstance',
            name='banType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bantype'),
        ),
    ]
