# Generated by Django 4.2.1 on 2023-07-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robloxuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
