# Generated by Django 4.2.1 on 2023-07-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_robloxuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='robloxuser',
            name='suspended_license',
            field=models.BooleanField(default=False),
        ),
    ]
